### ISSUE TITLE
How to merge? 

### ISSUE THREAD

**Issue by piliptsevich** [larshp/abapmerge#168]
npm install -> done
abapgit package exported -> done

How do I run merge for exported package? 

thanks

**Comment by larshp** [comment]
Hi,
The script for abapGit is located at https://github.com/abapGit/abapGit/blob/master/package.json#L5

it executes `abapmerge -f src/zabapgit.prog.abap -c zabapgit_standalone > zabapgit.abap`

note that there is a lot of caveats, eg. only global interfaces and classes are merged, and there must be a starting program to gather it all into

**Comment by piliptsevich** [comment]
Hi, 

thank you for quick response
