### ISSUE TITLE
possibility for merging global classes into local classes

### ISSUE THREAD

**Issue by larshp** [larshp/abapmerge#20]
problem: building the right sequence of definitions + implementations + uses

plus some classes in abapGit are dynamically referenced

**Comment by sbcgua** [comment]
Just a thought: there will be also an issue with class naming. E.g. prog_merged supposed to use local classes whereas prog_installed will use Z classes. Potentially, a universal factory class can be created to handle this based on some global switch (which in it's turn can be activated by something like `@@abammerge uncomment constants gc_merged type abap_bool value abap_true.`)

**Comment by larshp** [comment]
yeah, there is a lot of issues with this that has to be handled 😉 

I think it is allowed to have local classes named the same as global classes, eg `zcl_abapgit_foo` but it has to be tested.

**Comment by sbcgua** [comment]
Ha ! Cool ! Works indeed. Didn't know that :)

```abap
REPORT ZTEST68.

class zcl_mockup_loader definition.
  public section.
    class-methods: class_set_params.
endclass.

class zcl_mockup_loader implementation.
  method class_set_params.
    write: / 'From class'.
  endmethod.
endclass.

start-of-selection.

write: / 'Hello'.
ZCL_MOCKUP_LOADER=>CLASS_SET_PARAMS( ).
write: / 'End'.
```

![image](https://cloud.githubusercontent.com/assets/15635498/25779722/7e3768e6-3325-11e7-91c9-e7f5105e39e0.png)

**Comment by larshp** [comment]
biggest problem as I see it is the sequence of class DEFINITIONS and IMPLEMENTATIONs, all definitions could be added in the beginning of the file, however there are also some dependencies. I would like it to figure out the dependencies automagically via abaplint, but it is a lot of work

**Comment by larshp** [comment]
will try having abapGit export the contents of WBCROSSGT, think it has enough information, but not sure

**Comment by larshp** [comment]
also required: https://github.com/larshp/abapmerge/issues/9

**Comment by larshp** [comment]
0.7.0 released
