### ISSUE TITLE
Make timestamp programmatically accessible

### ISSUE THREAD

**Issue by fabianlupa** [larshp/abapmerge#373]
Hi,

would it be possible to add a constant to the marker interface (for abapGit)? Doing `READ REPORT` on a 100k+ lines report to parse one line of comments is quite the performance killer ;)

For example:

```abap
INTERFACE lif_abapmerge_marker.
* abapmerge 0.14.8 - 2023-01-09T17:14:22.870Z
  CONSTANTS merge_timestamp TYPE string VALUE `2023-01-09T17:14:22.870Z`.
ENDINTERFACE.
```

**Comment by larshp** [comment]
yea, pull request welcome
