### ISSUE TITLE
Includes ignored if there's extra stuff after the basic REPORT statement

### ISSUE THREAD

**Issue by pokrakam** [larshp/abapmerge#426]
Tests added to PR 434
Adding a comment to REPORT blocks include inclusion.
`REPORT zfoo LINE SIZE 100.` works but splitting it over multiple lines doesn't.

**Comment by larshp** [comment]
@pokrakam try again, 0.16.4 published

**Comment by pokrakam** [comment]
Works as expected, thanks.
