### ISSUE TITLE
How to use the Web Interface

### ISSUE THREAD

**Issue by RainerWinkler** [larshp/abapmerge#49]
Hi together,
I tried to use abapmerge. I clicked on http://larshp.github.io/abapmerge/ and dropped all files of the folder src onto it (the .abap and .xml). The program then says: "Select main file:" was is meant by this?
I tried the ZABAP files but nothing happens (Except a message).
What Do I wrong?

**Comment by larshp** [comment]
I dont think the web interface works anymore, it has not been updated for a while, but a lot of new stuff has been put into the core logic

**Comment by larshp** [comment]
the command used in abapGit:

https://github.com/larshp/abapGit/blob/master/travis.sh#L2

**Comment by larshp** [comment]
I've deleted the web interface, it still doesn't work after 2 years 😄 

closing
