### ISSUE TITLE
Demo site issue

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapmerge#5]
Hmmm does not work for me ... maybe I'm doing something wrong

![image](https://cloud.githubusercontent.com/assets/15635498/15317058/20d51ee0-1c20-11e6-92c9-e8ac35a41a8b.png)

src attached.
[code.zip](https://github.com/larshp/abapmerge/files/267778/code.zip)

**Comment by larshp** [comment]
no, try without subincludes, subinclues are not implemented, as I'm lazy :smile: I've opened issue #6 for it

**Comment by sbcgua** [comment]
same without subinclude :(
(removed the file and also reference in inc1)
[code2.zip](https://github.com/larshp/abapmerge/files/267855/code2.zip)

**Comment by larshp** [comment]
fixed in https://github.com/larshp/abapmerge/commit/5514472538bd9658106282f333df4961a3ea358b, try again, github page also updated

**Comment by sbcgua** [comment]
Works fine now :)
