### ISSUE TITLE
Ordering of interfaces

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapmerge#80]
from https://github.com/larshp/abapGit/issues/2525#issuecomment-473798647

`zif_abapgit_gui_renderable` appears after `zif_abapgit_gui_page` which is using it.

**Comment by larshp** [comment]
I'm on it

**Comment by larshp** [comment]
great, I broke it 😄 have a meeting now, back in an hour or so. Bug is in interface_parser.ts where it does substr(5)

**Comment by sbcgua** [comment]
no prob, there is a quick workaround, I wrote in 2525. So should be not that urgent :+1:

**Comment by sbcgua** [comment]
guess can be closed
